### ISSUE TITLE
bazzite-deck: Digital PCM Volume is lower than SteamOS default

### ISSUE THREAD

**Issue by Messaiga** [ublue-os/bazzite#137]
SteamOS Default ucm2 settings for the acp5x seem to have it output a bit louder than the defaults we pull from [jupiter-hw-support.](https://gitlab.com/evlaV/jupiter-hw-support)  If we can adjust the following params in [Hifi-Upstream.conf](https://gitlab.com/evlaV/jupiter-hw-support/-/blob/master/usr/share/alsa/ucm2/conf.d/acp5x/HiFi-upstream.conf?ref_type=heads) and [HiFi.conf](https://gitlab.com/evlaV/jupiter-hw-support/-/blob/master/usr/share/alsa/ucm2/conf.d/acp5x/HiFi.conf?ref_type=heads) it should match up properly.

`cset "name='Left Digital PCM Volume' 817"` -> `cset "name='Left Digital PCM Volume' 913"`
`cset "name='Right Digital PCM Volume' 817"` -> `cset "name='Right Digital PCM Volume' 913"`

**Comment by KyleGospo** [comment]
Addressed in https://github.com/ublue-os/bazzite/commit/f82baf75fbe5cb1f94614178d43608019e507f7c

Thank you so much!

**Comment by Messaiga** [comment]
Tested and the setting doesn't seem to have changed after receiving the update - on my Steam Deck I have another file in that directory with similar settings on it but I'm unsure which one ALSA is actually using.

/usr/share/alsa/ucm2/conf.d/acp5x/Valve-Jupiter-1.conf symlinked to /usr/share/alsa/ucm2/AMD/acp5x/acp5x.conf.

Can anyone confirm that they also have this present on their system?

**Comment by KyleGospo** [comment]
That file appears to be from upstream, additionally I found a syntax error in Valve's own and fixed that with a patch. Latest build removes that file and symlinks it to the location Valve uses on their end,

**Comment by Messaiga** [comment]
It definitely took effect this time.  It seems to be falling back to a different configuration profile rather than using the ones intended.  

This is what I get from `alsactl info 2`:

```
#
# Sound card
#
- card: 2
  id: acp5x
  name: acp5x
  longname: Valve-Jupiter-1
  driver_name: acp5x
  mixer_name: 
  components: 
  controls_count: 80
  pcm:
    - stream: PLAYBACK
      devices:
        - device: 0
          id: Playback/Capture nau8821-hifi-0
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
        - device: 1
          id: CS35L41 Stereo Playback multicodec-1
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0
    - stream: CAPTURE
      devices:
        - device: 0
          id: Playback/Capture nau8821-hifi-0
          name: 
          subdevices:
            - subdevice: 0
              name: subdevice #0

```
