### ISSUE TITLE
Global Flatpak overrides break app functionality

### ISSUE THREAD

**Issue by ImDevinC** [ublue-os/bazzite#2332]
### Describe the bug

https://github.com/ublue-os/bazzite/blob/main/system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager#L43
Bazzite runs this command to globaly make the `xdg-data/icons` folder read-only. However, this folder equates to `~/.var/app/<app>/data/icons`, which is a logical place to store icons specific for the usage of the application.

### What did you expect to happen?

 I would not expect Bazzite to lock me out of creating/writing to folders inside of my own application workspace.

### Output of `rpm-ostree status`

```shell
I am not a bazzite user, so I don't have access to this. This original report came from a user.
```

### Extra information or context

Here's a very simple flatpak that can reproduce this issue
```yaml
id: com.imdevinc.IconTest
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: hello
modules:
  - name: hello
    buildsystem: simple
    build-commands:
      - install -Dm755 hello.sh /app/bin/hello
    sources:
      - type: script
        dest-filename: hello.sh
        commands:
          - echo "Hello world, from a sandbox"
          - mkdir -p $XDG_DATA_HOME/icons
          - touch $XDG_DATA_HOME/icons/test-icon
```
