### ISSUE TITLE
Waking from suspend doesn't work with Nvidia Gnome

### ISSUE THREAD

**Issue by pradaker** [ublue-os/bazzite#2437]
### Describe the bug

I had been using Bazzite with KDE Plasma for a few months without issue. Yesterday, I decided to reinstall Bazzite but this time with Gnome, and most things have been fine. However, I am now not able to wake my PC from sleep. When I try, my display powers on for a brief moment, and then shuts off. The PC still has power, but it's not connected to the network, my keyboard/mouse doesn't seem to do anything, and even the power button does nothing unless I hold it down to forcefully shut it off.

System logs: https://paste.centos.org/view/85e837b0

System info: https://paste.centos.org/view/9f1ff574

### What did you expect to happen?

I expected the system to wake up and resume

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable
                   Digest: sha256:e8fdf9440b2231b75939652c21c3134a43f05135cbe4a547d1f2a5423ca01913
                  Version: 41.20250325 (2025-03-25T20:32:46Z)
          LayeredPackages: openrazer-daemon

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:9459dfc02f5d3c4bb9aba135333002e7021cb364e435fa51eacdca52e41ff72e
                  Version: 41.20250325 (2025-03-25T20:29:21Z)
          LayeredPackages: openrazer-daemon
```

### Hardware

Mobo: Asus ROG STRIX B650E-F Gaming WiFi
CPU: AMD Ryzen 9 7900X
GPU: Nvidia GeForce RTX 4090
RAM: 32GB

### Extra information or context

I didn't change any hardware during the switch from KDE Plasma to Gnome

**Comment by tduarte** [comment]
Installed Bazzite last night and I'm having the same issue.

**Comment by SanelessOne** [comment]
I wonder if you're having the same issue as me

https://github.com/ublue-os/bazzite/issues/2429

**Comment by natesevn** [comment]
FWIW, I have the same issue with `bazzite-gnome-nvidia-open`. I've also encountered the same with the KDE version `bazzite-nvidia-open`. It sounds like there was an issue with the `MT7922` Wifi card module that was [fixed as of Linux 6.12.8](https://bbs.archlinux.org/viewtopic.php?id=295916), but I'm still seeing it on Linux 6.13.7.

**Comment by tduarte** [comment]
@natesevn I’m running an Intel WiFi card, it looks like the only common denominator is the NVIDIA gpu.

**Comment by natesevn** [comment]
I was browsing through more user issues and came across this one which perfectly describes what I'm seeing: https://github.com/ublue-os/bazzite/issues/1904

Interestingly enough, it repros on AMD GPUs too.

**Comment by HopeSilent** [comment]
Can also confirm this issue is present for me on bazzite gnome with nvidia closed. It's running on a Ryzen 5 5600T in a Asrock B450m Pro4 with a GTX 1070. No ability to resume from suspend (no video output), have to hold the power button to force it off and then freshly boot up. This [post]((https://old.reddit.com/r/Fedora/comments/1epr6eg/black_screen_on_sleepwake_bazzite/)](url)) by Radioactive_Doomer on Reddit appears to discuss a similar issue that was resolved by doing the following:

"In case anyone else has this issue I fixed it. It was combination of AMD IOMMU making the gfx card inaccessible and some pci device controller triggering wake up.

I set amd_iommu=off in the GRUB command line options and used /proc/acpi/wakeup to find the offending device and disable wake signals."

This is the only reference I've found to the issue, indicating it was something to do with IOMMU, which I've already verified is disabled in my BIOS.

**Comment by Colcobau** [comment]
Having the exact same issue on my machine for the last couple of weeks. This only started recently, and was not an issue before.

![Image](https://github.com/user-attachments/assets/ceffcb1d-bfb0-49f8-8e0f-7418c1fe9b57)

Turning off IOMMU is not really an option for me.

**Comment by kumail-r** [comment]
@Colcobau I see you might have missed the solution [linked](https://bbs.archlinux.org/viewtopic.php?pid=2044189#p2044189) in the issue by OP, I just tried it and it worked for me (similar background, this problem started a few weeks ago on my system with an RTX 3090 + Ryzen 7000 CPU).

Instructions:
1. Create `/usr/local/bin/suspend-gnome-shell.sh` and put this script in it: 
```bash
#!/bin/bash

case "$1" in
    suspend)
        killall -STOP gnome-shell
        ;;
    resume)
        killall -CONT gnome-shell
        ;;
esac
```

2. Do the same for `/etc/systemd/system/gnome-shell-suspend.service`:

```TOML
[Unit]
Description=Suspend gnome-shell
Before=systemd-suspend.service
Before=systemd-hibernate.service
Before=nvidia-suspend.service
Before=nvidia-hibernate.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/suspend-gnome-shell.sh suspend

[Install]
WantedBy=systemd-suspend.service
WantedBy=systemd-hibernate.service
```

3. Do the same for `/etc/systemd/system/gnome-shell-resume.service`:

```TOML
[Unit]
Description=Resume gnome-shell
After=systemd-suspend.service
After=systemd-hibernate.service
After=nvidia-resume.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/suspend-gnome-shell.sh resume

[Install]
WantedBy=systemd-suspend.service
WantedBy=systemd-hibernate.service
```

4. Finally, run these commands:

```shell
systemctl daemon-reload
systemctl enable gnome-shell-suspend
systemctl enable gnome-shell-resume
```
